In [1]:
import numpy as np

In [2]:
a = np.random.randint(2, size=(10, 10), dtype=np.uint8)

In [3]:
print(a)

[[1 0 0 1 0 1 0 0 0 1]
 [0 0 0 1 0 1 1 0 1 0]
 [0 1 0 1 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 1 0 1]
 [0 1 1 1 0 1 0 0 1 1]
 [1 0 1 1 1 0 1 0 1 0]
 [1 0 1 1 1 0 1 0 0 1]
 [0 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1]
 [0 1 0 1 0 0 0 0 0 0]]


In [4]:
b = np.zeros_like(a)
rows, cols = a.shape
for i in range(1, rows-1):
    for j in range(1, cols-1):
        state = a[i, j]
        neighbors = a[i-1:i+2, j-1:j+2]
        k = np.sum(neighbors) - state
        if state:
            if k == 2 or k == 2:
                b[i, j] = 1
        else:
            if k == 3:
                b[i, j] = 1

In [12]:
print(b)

[[0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0 1 1 1]
 [0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [6]:
from scipy.signal import correlate2d

In [7]:
kernel = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
c = correlate2d(a, kernel, mode='same')

In [9]:
b = (c==3) | (c==2) & a
b = b.astype(np.uint8)

In [11]:
kernel = np.array([[1, 1, 1], [1, 10, 1], [1, 1, 1]])
c = correlate2d(a, kernel, mode='same')
b = (c==3) | (c==12) | (c==13)
b = b.astype(np.uint8)